name: linux

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run script
        run: echo `pwd`

      - name: Upload content
        uses: actions/upload-artifact@v3
        with:
          name: static-site
          path: ./
