name: linux

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run script
        run: cd / & mkdir /out & cd /out & touch /out/a.txt & echo 111 > /out/a.txt

      - name: Download content
        uses: actions/upload-artifact@v3
        with:
          name: static-site
          path: out/
